FROM ubuntu:21.10

ENV MONERO_HASH 59e16c53b2aff8d9ab7a8ba3279ee826ac1f2480fbb98e79a149e6be23dd9086
ENV MONERO_DL_URL https://downloads.getmonero.org/cli/monero-linux-x64-v0.17.2.0.tar.bz2
ENV MONERO_DL_FILE monero.tar.bz2
ENV MONERO_SUMS_FILE sha256sums

WORKDIR /opt/monero

# Update system and install dependencies
# Download Monero binaries from Github
# Confirm hashes match
# Install binaries to system path
# Clean up

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y tar wget bzip2

RUN wget -qO ${MONERO_DL_FILE} ${MONERO_DL_URL}
RUN echo "${MONERO_HASH}  ${MONERO_DL_FILE}" > ${MONERO_SUMS_FILE} \
  && sha256sum -c ${MONERO_SUMS_FILE}; \
  if [ "$?" -eq 0 ]; \
  then \
    echo -e "[+] Hashes match - proceeding with container build"; \
  else \
    echo -e "[!] Hashes do not match - exiting"; \
    exit 5; \
  fi \
  && mkdir ./tmp \
  && tar xvf ${MONERO_DL_FILE} -C ./tmp --strip 1 \
  && mv ./tmp/* /usr/local/bin/ \
  && rm -rf ./tmp ${MONERO_SUMS_FILE} ${MONERO_DL_FILE}

WORKDIR /tmp
COPY bin/run_wallet.sh /run_wallet.sh

WORKDIR /data
